### ISSUE TITLE
Do not allow path traversal by default when pushing package

### ISSUE THREAD

**Issue by yuwaMSFT2** [deislabs/oras#57]
Do not allow path traversal by default when pushing package. It's a gesture to indicate that the tool considers this as a potential security issue, and it helps to avoid generating package with security hole unexpected. User may choose to allow it but it should not be the default

**Comment by shizhMSFT** [comment]
The path traversal validation on read should be checked not only on the `FileStore` but also on all the content stores. Therefore, it should be considered as an option in the `pkg/oras` pakage.

The implementation of the resolution will start after merging #56 since it will be based on the implemented push options.
